unit HandleMenu;

interface

procedure Main;

implementation

uses
  Activity1 in '../questions/Activity1.pas',
  Activity2 in '../questions/Activity2.pas',
  Activity3 in '../questions/Activity3.pas',
  Activity4 in '../questions/Activity4.pas',
  Activity5 in '../questions/Activity5.pas',
  Activity6 in '../questions/Activity6.pas',
  Activity7 in '../questions/Activity7.pas',
  Activity8 in '../questions/Activity8.pas',
  Activity9 in '../questions/Activity9.pas',
  Activity10 in '../questions/Activity10.pas',
  Activity11 in '../questions/Activity11.pas',
  Activity12 in '../questions/Activity12.pas',
  Activity13 in '../questions/Activity13.pas', 
  Activity14 in '../questions/Activity14.pas',
  Activity15 in '../questions/Activity15.pas',
  Activity16 in '../questions/Activity16.pas',
  Activity17 in '../questions/Activity17.pas',
  Activity18 in '../questions/Activity18.pas',
  Activity19 in '../questions/Activity19.pas',
  Activity20 in '../questions/Activity20.pas',
  Activity21 in '../questions/Activity21.pas',
  Activity22 in '../questions/Activity22.pas',
  Activity23 in '../questions/Activity23.pas',
  Activity24 in '../questions/Activity24.pas',
  Activity25 in '../questions/Activity25.pas',
  Activity26 in '../questions/Activity26.pas',
  Activity27 in '../questions/Activity27.pas',
  Activity28 in '../questions/Activity28.pas',
  Activity29 in '../questions/Activity29.pas',
  Activity30 in '../questions/Activity30.pas',
  Activity31 in '../questions/Activity31.pas',
  Activity32 in '../questions/Activity32.pas',
  Activity33 in '../questions/Activity33.pas',
  Activity34 in '../questions/Activity34.pas',
  Activity35 in '../questions/Activity35.pas',
  Activity36 in '../questions/Activity36.pas',
  Activity37 in '../questions/Activity37.pas',
  Activity38 in '../questions/Activity38.pas',
  Activity39 in '../questions/Activity39.pas',
  Activity40 in '../questions/Activity40.pas',
  Activity41 in '../questions/Activity41.pas',
  Activity42 in '../questions/Activity42.pas',
  Activity43 in '../questions/Activity43.pas',
  Activity44 in '../questions/Activity44.pas',
  Activity45 in '../questions/Activity45.pas',
  Activity46 in '../questions/Activity46.pas',
  Activity47 in '../questions/Activity47.pas',
  Activity48 in '../questions/Activity48.pas';

var
  Activities: array[1..48] of procedure = (
    Activity1.Main,
    Activity2.Main,
    Activity3.Main,
    Activity4.Main,
    Activity5.Main,
    Activity6.Main,
    Activity7.Main,
    Activity8.Main,
    Activity9.Main,
    Activity10.Main,
    Activity11.Main,
    Activity12.Main,
    Activity13.Main,
    Activity14.Main,
    Activity15.Main,
    Activity16.Main,
    Activity17.Main,
    Activity18.Main,
    Activity19.Main,
    Activity20.Main,
    Activity21.Main,
    Activity22.Main,
    Activity23.Main,
    Activity24.Main,
    Activity25.Main,
    Activity26.Main,
    Activity27.Main,
    Activity28.Main,
    Activity29.Main,
    Activity30.Main,
    Activity31.Main,
    Activity32.Main,
    Activity33.Main,
    Activity34.Main,
    Activity35.Main,
    Activity36.Main,
    Activity37.Main,
    Activity38.Main,
    Activity39.Main,
    Activity40.Main,
    Activity41.Main,
    Activity42.Main,
    Activity43.Main,
    Activity44.Main,
    Activity45.Main,
    Activity46.Main,
    Activity47.Main,
    Activity48.Main
  );
